language: node_js

node_js:
  - '6.1'
  - '8.4'
  - '8.9.1'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  - npm run prettier:diff
  - npm run test
