# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: "."
          key: ${{ github.sha }}
          
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - run: yarn eslint:ci

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - run: yarn test
